apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/nirroolat/microtrader:{{.VERSION}}"
  artifacts:
  - imageName: microtrader
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/nirroolat/microtrader:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: microtrader
        chartPath: charts/microtrader
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/nirroolat/microtrader"
          image.tag: "{{.DIGEST_HEX}}"
